@startuml
title Публикация товара на маркетплейсе (улучшенный сценарий)

start

:Войти в Личный кабинет;
:Перейти в раздел "Товары";
:Нажать "Добавить товар";

:Заполнить обязательные поля
(название, описание, категория,
характеристики, цена, количество);

:Заполнить необязательные поля
(видео, SEO, варианты товара и т.д.);

:Загрузить фотографии (минимум 1);

repeat
  if (Все обязательные поля корректны?) then (да)
    break
  else (нет)
    :Показать ошибки валидации;
    :Исправить ошибки;
  endif
repeat while (true)

:Нажать "Предпросмотр";
:Просмотреть, как товар будет выглядеть на витрине;

:Нажать "Опубликовать или Отправить на модерацию";

if (Продавец имеет право публикации?) then (нет)
  :Показать сообщение "Нет прав публикации";
  stop
endif

if (Требуется модерация?) then (да)
  :Товар переходит в статус "На модерации";
  :Показать уведомление "Товар отправлен на проверку";

  if (Модератор одобрил товар?) then (нет)
    :Показать уведомление "Товар отклонен";
    :Продавец исправляет товар;
    -> "Нажать 'Опубликовать или Отправить на модерацию'"
  else (да)
    :Товар публикуется на витрине;
    :Показать уведомление об успешной публикации;
  endif

else (нет)
  :Товар публикуется на витрине;
  :Показать уведомление об успешной публикации;
endif

:Отправить уведомление на e-mail (опционально);

stop
@enduml
